### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [snakypy/snakypy-prompt-shellscript#1]
Please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

**Comment by williamcanin** [comment]
@unixorn Thanks for the feedback, but the project is currently under development.

**Comment by unixorn** [comment]
ok, let me know when it's ready for release

**Comment by williamcanin** [comment]
@unixorn Well, I don't have an accurate **prediction**, but soon. I am creating a package to manage the theme. With the ability to **enable** and **disable**, **install** and **uninstall** more automatically, and other features.

**Comment by unixorn** [comment]
Sounds interested, I look forward to seeing the final result.

**Comment by williamcanin** [comment]
The long awaited stable release of **Snakypy Prompt** has arrived!
_Version_: [1.0.0](https://github.com/snakypy/snakypy-prompt/releases/tag/v1.0.0)
Learn more at: [Snakypy Prompt](https://github.com/snakypy/snakypy-prompt)
